# change this to the abc binary path if the command is not recognized system-wide
abc_binary: yosys-abc
yosys_binary: yosys

# path of the design file in one of the accepted formats by ABC
design_file: adder.v

# standard cell library mapping
mapping:
  clock_period: 1800   # in pico seconds
  library_file: asap7.lib

# FPGA mapping - exlusive with the above
fpga_mapping:
  levels: 100
  lut_inputs: 6

# add more optimization to the toolbox
optimizations:
  - rewrite
  - rewrite -z
  - refactor
  - refactor -z
  - resub
  - resub -z
  - balance

# the directory to hold the playground an agent uses to practice
playground_dir: playground

# agent training parameters
episodes: 1
iterations: 10
model_dir: /tmp/model.ckpt   # must be absolute path