/* Generated by Yosys 0.36 (git sha1 8f07a0d8404, clang 15.0.0 -fPIC -Os) */

(* src = "design.v:1.1-56.10" *)
module FloatingPointAdder(operand_a_mantissa, operand_b_mantissa, operand_a_exponent, operand_b_exponent, operand_a_sign, operand_b_sign, result_mantissa, result_exponent, result_sign);
  reg \$auto$verilog_backend.cc:2189:dump_module$9  = 0;
  (* src = "design.v:20.3-52.6" *)
  reg [8:0] _00_;
  (* src = "design.v:20.3-52.6" *)
  reg [8:0] _01_;
  (* src = "design.v:20.3-52.6" *)
  reg [3:0] _02_;
  (* src = "design.v:20.3-52.6" *)
  reg [3:0] _03_;
  (* src = "design.v:20.3-52.6" *)
  reg [2:0] _04_;
  (* src = "design.v:20.3-52.6" *)
  reg [2:0] _05_;
  (* src = "design.v:20.3-52.6" *)
  reg _06_;
  (* src = "design.v:20.3-52.6" *)
  reg [8:0] _07_;
  (* src = "design.v:20.3-52.6" *)
  reg [8:0] _08_;
  (* src = "design.v:20.3-52.6" *)
  reg [3:0] _09_;
  (* src = "design.v:20.3-52.6" *)
  reg [2:0] _10_;
  (* src = "design.v:20.3-52.6" *)
  reg _11_;
  (* src = "design.v:20.3-52.6" *)
  reg [8:0] _12_;
  (* src = "design.v:38.22-38.79" *)
  wire [8:0] _13_;
  (* src = "design.v:45.25-45.66" *)
  wire [2:0] _14_;
  (* src = "design.v:29.9-29.33" *)
  wire _15_;
  (* src = "design.v:31.14-31.38" *)
  wire _16_;
  (* src = "design.v:32.38-32.59" *)
  wire [2:0] _17_;
  (* src = "design.v:26.28-26.67" *)
  wire [2:0] _18_;
  (* src = "design.v:36.22-36.79" *)
  wire [8:0] _19_;
  (* src = "design.v:13.13-13.40" *)
  reg [8:0] extended_operand_a_mantissa;
  (* src = "design.v:14.13-14.40" *)
  reg [8:0] extended_operand_b_mantissa;
  (* src = "design.v:15.13-15.25" *)
  reg [3:0] mantissa_sum;
  (* src = "design.v:16.13-16.36" *)
  reg [3:0] normalized_mantissa_sum;
  (* src = "design.v:4.15-4.33" *)
  input [2:0] operand_a_exponent;
  wire [2:0] operand_a_exponent;
  (* src = "design.v:2.15-2.33" *)
  input [7:0] operand_a_mantissa;
  wire [7:0] operand_a_mantissa;
  (* src = "design.v:6.9-6.23" *)
  input operand_a_sign;
  wire operand_a_sign;
  (* src = "design.v:5.15-5.33" *)
  input [2:0] operand_b_exponent;
  wire [2:0] operand_b_exponent;
  (* src = "design.v:3.15-3.33" *)
  input [7:0] operand_b_mantissa;
  wire [7:0] operand_b_mantissa;
  (* src = "design.v:7.9-7.23" *)
  input operand_b_sign;
  wire operand_b_sign;
  (* src = "design.v:9.16-9.31" *)
  output [2:0] result_exponent;
  reg [2:0] result_exponent;
  (* src = "design.v:17.13-17.33" *)
  reg [2:0] result_exponent_diff;
  (* src = "design.v:8.16-8.31" *)
  output [7:0] result_mantissa;
  wire [7:0] result_mantissa;
  (* src = "design.v:10.10-10.21" *)
  output result_sign;
  reg result_sign;
  assign _13_ = _07_ + (* src = "design.v:38.22-38.79" *) _08_;
  assign _14_ = operand_a_exponent + (* src = "design.v:45.25-45.66" *) _18_;
  assign _15_ = _18_ > (* src = "design.v:29.9-29.33" *) 32'd0;
  assign _16_ = _18_ < (* src = "design.v:31.14-31.38" *) 32'd0;
  assign _17_ = - (* src = "design.v:32.38-32.59" *) _18_;
  assign _18_ = operand_a_exponent - (* src = "design.v:26.28-26.67" *) operand_b_exponent;
  assign _19_ = _07_ - (* src = "design.v:36.22-36.79" *) _08_;
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$9 ) begin end
    _05_ = _18_;
    _00_ = _07_;
    _01_ = _08_;
    _02_ = _09_;
    _03_ = 4'hx;
    _04_ = _10_;
    _06_ = _11_;
    (* src = "design.v:29.5-32.81" *)
    casez (_15_)
      /* src = "design.v:29.9-29.33" */
      1'h1:
        begin
          _07_ = { 1'h0, operand_a_mantissa };
          _08_ = { _18_[0], operand_b_mantissa };
        end
      /* src = "design.v:31.5-31.9" */
      default:
        begin
          _08_ = { 1'h0, operand_b_mantissa };
          _07_ = _12_;
          (* src = "design.v:31.10-32.81" *)
          casez (_16_)
            /* src = "design.v:31.14-31.38" */
            1'h1:
                _12_ = { _17_[0], operand_a_mantissa };
            default:
                _12_ = { 1'h0, operand_a_mantissa };
          endcase
        end
    endcase
    (* src = "design.v:35.5-38.80" *)
    casez (operand_b_sign)
      /* src = "design.v:35.9-35.23" */
      1'h1:
          _09_ = _19_[3:0];
      /* src = "design.v:37.5-37.9" */
      default:
          _09_ = _13_[3:0];
    endcase
    (* src = "design.v:44.5-51.8" *)
    casez (1'hx)
      /* src = "design.v:44.9-44.24" */
      1'h1:
        begin
          _10_ = _14_;
          _11_ = operand_a_sign;
        end
      /* src = "design.v:48.5-48.9" */
      default:
        begin
          _10_ = operand_b_exponent;
          _11_ = operand_b_sign;
        end
    endcase
  end
  always @* begin
      result_exponent <= _04_;
      result_sign <= _06_;
      extended_operand_a_mantissa <= _00_;
      extended_operand_b_mantissa <= _01_;
      mantissa_sum <= _02_;
      normalized_mantissa_sum <= _03_;
      result_exponent_diff <= _05_;
  end
  assign result_mantissa = { 4'h0, normalized_mantissa_sum };
endmodule
